# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-25 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_task_card_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='card_name',
            new_name='task_name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='card_description',
        ),
    ]
