# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-25 01:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20170425_0654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_name',
            new_name='card_name',
        ),
        migrations.AddField(
            model_name='task',
            name='card_description',
            field=models.CharField(default=11, max_length=800),
            preserve_default=False,
        ),
    ]
