# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-25 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.task'),
        ),
    ]
