# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-25 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20170425_1100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='task',
            new_name='tasks',
        ),
    ]
