# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-25 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_auto_20170425_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_name',
            field=models.CharField(max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='tasks',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='board.task'),
        ),
    ]
