# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-25 10:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0009_auto_20170425_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_name',
            field=models.CharField(default=12, max_length=55),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='tasks',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='board.task'),
            preserve_default=False,
        ),
    ]
