# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-25 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_auto_20170425_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='Comments',
            field=models.CharField(default=45, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='card_name',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
